language: dart
sudo: false
dart:
  - stable
cache:
  directories:
    - $HOME/.pub-cache
with_content_shell: true
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - 't=0; until (xdpyinfo -display :99 &> /dev/null || test $t -gt 10); do sleep 1; let t=$t+1; done'
script:
  - pub get
  - set -e
  - pub run test -p content-shell test/browser/travis_sniff_test.dart
  - pub run dart_dev test
  - pub run dart_dev coverage --no-html
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.lcov