language: dart
sudo: false
dart:
  - stable
cache:
  directories:
    - $HOME/.pub-cache
with_content_shell: true
script:
  - pub get
  - set -e
  - pub run test -p content-shell test/browser/travis_sniff_test.dart
  - pub run dart_dev test