name: 'currency_converter'
version: 0.0.1
description: A web app to check currency exchange rates.
environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  js: "0.6.1"

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
  test: '0.12.17+2'
  mockito: "1.0.1"
  dart_coveralls: "0.4.0"

transformers:
- dart_to_js_script_rewriter
