name: 'currency_converter'
version: 0.0.1
description: A web app to check currency exchange rates.
environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  js: any

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
  mockito: "1.0.1"
  coverage: "^0.7.3"
  dart_dev: "^1.0.0"
  dart_style: ">=0.2.0 <0.3.0"
  dartdoc: ">=0.8.0 <=0.10.0"
  test: ^0.12.6

transformers:
- dart_to_js_script_rewriter
